//! Embed PostHog project credentials at frontend build time.
//!
//! Writes `public/posthog-config.js` consumed by `index.html`, and sets
//! `POSTHOG_*` rustc-env vars if the WASM crate needs them later.
//!
//! Source (first wins): process env → workspace `../.env` → local `.env`.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
  load_dotenv_if_present(Path::new("../.env"));
  load_dotenv_if_present(Path::new(".env"));

  let api_key = env::var("POSTHOG_API_KEY").unwrap_or_default();
  let host = env::var("POSTHOG_HOST").unwrap_or_else(|_| "https://us.i.posthog.com".into());

  if !api_key.trim().is_empty() {
    println!("cargo:rustc-env=POSTHOG_API_KEY={}", api_key.trim());
  }
  if !host.trim().is_empty() {
    println!("cargo:rustc-env=POSTHOG_HOST={}", host.trim());
  }
  println!("cargo:rerun-if-env-changed=POSTHOG_API_KEY");
  println!("cargo:rerun-if-env-changed=POSTHOG_HOST");
  // Only watch env files that exist — missing paths can make Cargo re-run build.rs every build.
  for env_path in ["../.env", ".env"] {
    if Path::new(env_path).is_file() {
      println!("cargo:rerun-if-changed={env_path}");
    }
  }

  write_posthog_config(api_key.trim(), host.trim());
}

fn write_posthog_config(api_key: &str, host: &str) {
  let public = Path::new("public");
  if let Err(e) = fs::create_dir_all(public) {
    println!("cargo:warning=could not create public/: {e}");
    return;
  }

  let host = if host.is_empty() {
    "https://us.i.posthog.com"
  } else {
    host
  };

  // Escape for a JS string literal (double-quoted).
  let key_js = escape_js_string(api_key);
  let host_js = escape_js_string(host);

  let body = format!(
    r#"// AUTO-GENERATED by app-ui/build.rs — do not edit.
// PostHog project API key is injected at build time from POSTHOG_API_KEY.
// Empty key → analytics JS stays disabled for this build.
window.__CDX_POSTHOG__ = {{
  key: "{key_js}",
  host: "{host_js}"
}};
"#
  );

  let path = public.join("posthog-config.js");
  // Never `rerun-if-changed` this path: writing it would retrigger build.rs forever.
  // Only write when content actually changes so Trunk's file watcher does not loop.
  match fs::read_to_string(&path) {
    Ok(existing) if existing == body => {}
    _ => {
      if let Err(e) = fs::write(&path, body) {
        println!("cargo:warning=could not write {}: {e}", path.display());
      }
    }
  }
}

fn escape_js_string(s: &str) -> String {
  let mut out = String::with_capacity(s.len());
  for c in s.chars() {
    match c {
      '\\' => out.push_str("\\\\"),
      '"' => out.push_str("\\\""),
      '\n' => out.push_str("\\n"),
      '\r' => out.push_str("\\r"),
      '\u{2028}' => out.push_str("\\u2028"),
      '\u{2029}' => out.push_str("\\u2029"),
      c if c.is_control() => out.push_str(&format!("\\u{:04x}", c as u32)),
      c => out.push(c),
    }
  }
  out
}

fn load_dotenv_if_present(path: &Path) {
  let Ok(raw) = fs::read_to_string(path) else {
    return;
  };
  for line in raw.lines() {
    let line = line.trim();
    if line.is_empty() || line.starts_with('#') {
      continue;
    }
    let Some((key, value)) = line.split_once('=') else {
      continue;
    };
    let key = key.trim();
    if key.is_empty() || env::var_os(key).is_some() {
      continue;
    }
    let value = value.trim().trim_matches(|c| c == '"' || c == '\'');
    // SAFETY: single-threaded build script; only sets missing vars.
    unsafe { env::set_var(key, value) };
  }
}
